# Generated by Django 5.2.17 on 2026-09-20 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('preference', models.CharField(choices=[('email', 'Reply by email'), ('call', 'Call me back')], default='email', max_length=10)),
                ('message', models.TextField()),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='No leading domain. Examples: /account/ (prefix) or /board/report.pdf (exact).', max_length=200)),
                ('match_type', models.CharField(choices=[('exact', 'Exact path'), ('prefix', 'Path prefix')], default='prefix', max_length=10)),
                ('title', models.CharField(blank=True, help_text="Shown on the login page ('you need to sign in to view <title>').", max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Skeleton', max_length=120)),
                ('canonical_origin', models.CharField(default='http://127.0.0.1:8000', help_text='Used for canonical URLs, hreflang, JSON-LD, sitemap, IndexNow. No trailing slash.', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('default_meta_description', models.CharField(blank=True, default='A production-shaped Django skeleton: consent-first tracking, SEO suite, lazy sections, Lottie.', max_length=300)),
                ('theme_color', models.CharField(default='#0b0d10', max_length=9)),
                ('enable_cookie_consent', models.BooleanField(default=True, help_text='Master switch for the Klaro! consent manager and banner.')),
                ('consent_cookie_name', models.CharField(default='skeleton_consent', max_length=64)),
                ('enable_tracking', models.BooleanField(default=False, help_text='Master switch. A tracker loads only when this is on AND its ID below is filled in.')),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=32)),
                ('google_analytics_measurement_id', models.CharField(blank=True, max_length=32)),
                ('google_ads_id', models.CharField(blank=True, max_length=32)),
                ('google_ads_conversion_label', models.CharField(blank=True, max_length=64)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=64)),
                ('linkedin_partner_id', models.CharField(blank=True, max_length=32)),
                ('microsoft_ads_uet_tag_id', models.CharField(blank=True, max_length=64)),
                ('microsoft_clarity_project_id', models.CharField(blank=True, max_length=32)),
                ('hotjar_site_id', models.CharField(blank=True, max_length=16)),
                ('tiktok_pixel_id', models.CharField(blank=True, max_length=64)),
                ('pinterest_tag_id', models.CharField(blank=True, max_length=32)),
                ('x_twitter_pixel_id', models.CharField(blank=True, max_length=32)),
                ('matomo_url', models.CharField(blank=True, help_text='Self-hosted Matomo base URL, e.g. https://analytics.example.com', max_length=200)),
                ('matomo_site_id', models.CharField(blank=True, max_length=8)),
                ('enable_sitemap', models.BooleanField(default=True)),
                ('enable_robots_txt', models.BooleanField(default=True)),
                ('enable_llms_txt', models.BooleanField(default=True, help_text='Serves /llms.txt and /llms-full.txt for AI crawlers.')),
                ('enable_jsonld', models.BooleanField(default=True)),
                ('enable_indexnow', models.BooleanField(default=False)),
                ('indexnow_key', models.CharField(blank=True, default='', help_text='IndexNow key. The <key>.txt proof route only matches this value.', max_length=128)),
                ('google_site_verification', models.CharField(blank=True, max_length=128)),
                ('bing_site_verification', models.CharField(blank=True, max_length=128)),
                ('facebook_domain_verification', models.CharField(blank=True, max_length=128)),
                ('pinterest_domain_verification', models.CharField(blank=True, max_length=128)),
                ('robots_noindex_whole_site', models.BooleanField(default=False, help_text='Staging kill switch: X-Robots-Tag noindex on every page.')),
                ('enable_contact_form', models.BooleanField(default=True)),
                ('enable_turnstile', models.BooleanField(default=False, help_text='Cloudflare Turnstile on the contact form. Keys come from env or the fields below.')),
                ('turnstile_site_key', models.CharField(blank=True, max_length=128)),
                ('turnstile_secret_key', models.CharField(blank=True, max_length=128)),
                ('enable_honeypot', models.BooleanField(default=True)),
                ('form_min_seconds', models.PositiveIntegerField(default=3, help_text='Signed time-trap: bots that submit faster are silently discarded.')),
                ('contact_rate_limit_seconds', models.PositiveIntegerField(default=300, help_text='Per-session cooldown between contact form submissions.', validators=[django.core.validators.MinValueValidator(10)])),
                ('enable_public_registration', models.BooleanField(default=True)),
                ('registration_requires_approval', models.BooleanField(default=False, help_text='New users are created inactive; an admin activates them in People.')),
                ('enable_calcom_embed', models.BooleanField(default=False)),
                ('calcom_link', models.CharField(blank=True, max_length=200)),
                ('enable_stripe_buy_button', models.BooleanField(default=False)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=128)),
                ('stripe_buy_button_id', models.CharField(blank=True, max_length=128)),
                ('enable_scraper_block', models.BooleanField(default=True, help_text='403 known scraper user agents on legal/personal-data pages.')),
                ('enable_csp', models.BooleanField(default=True, help_text='Content-Security-Policy header (skipped on /admin/).')),
                ('enable_external_link_handling', models.BooleanField(default=True, help_text='Outbound link snatcher: tags external anchors with data-external + rel=noopener noreferrer.')),
                ('external_link_utm', models.BooleanField(default=True, help_text='Append utm_source=<your host> to outbound links.')),
                ('external_link_modal', models.BooleanField(default=False, help_text='Show the leave-site confirmation modal for outbound clicks.')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
