# Generated by Django 5.2.17 on 2026-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='theme_color',
            field=models.CharField(default='#fcfcfa', max_length=9),
        ),
    ]
