# Generated by Django 5.2.17 on 2026-09-20 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siteconfiguration_external_link_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(default='cybersecurity', max_length=80)),
                ('content', models.TextField(help_text='Plain text. Blank lines become paragraphs.')),
                ('meta_description', models.CharField(max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Optional comma-separated search terms.', max_length=300)),
                ('excerpt', models.CharField(max_length=320)),
                ('author_name', models.CharField(default='Editorial team', max_length=120)),
                ('hero_image', models.ImageField(blank=True, upload_to='articles/hero/')),
                ('hero_image_alt', models.CharField(blank=True, max_length=200)),
                ('hero_image_caption', models.CharField(blank=True, max_length=240)),
                ('hero_image_credit', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to='articles/og/')),
                ('seo_title', models.CharField(blank=True, max_length=110)),
                ('show_disclaimer', models.BooleanField(default=False)),
                ('show_ai_disclosure', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_articles',
            field=models.BooleanField(default=True, help_text='Publishes article index and detail pages and exposes their links.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_bottom_left',
            field=models.CharField(blank=True, default='All public content is controlled from the admin.', max_length=180),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_bottom_right',
            field=models.CharField(blank=True, default='Django 5.2 · zero build step · output minified', max_length=180),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_note',
            field=models.CharField(blank=True, default='A production-shaped Django skeleton. Change the site from the control panel.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='starter_content_seeded',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/content/')),
                ('alt_text', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('credit', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.article')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('link', 'Link'), ('text', 'Text block'), ('media', 'Logo or image'), ('action', 'Site action')], default='link', max_length=12)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('page', models.CharField(blank=True, choices=[('custom', 'Custom URL'), ('home', 'Home'), ('demo', 'Demo'), ('articles', 'Articles'), ('contact', 'Contact'), ('account', 'Account'), ('login', 'Sign in'), ('register', 'Register'), ('admin', 'Admin'), ('privacy', 'Privacy'), ('imprint', 'Imprint'), ('accessibility', 'Accessibility'), ('robots', 'robots.txt'), ('sitemap', 'sitemap.xml'), ('llms', 'llms.txt'), ('llms_full', 'llms-full.txt'), ('security', 'security.txt'), ('humans', 'humans.txt')], default='custom', max_length=20)),
                ('url', models.CharField(blank=True, help_text='Used only for Custom URL links.', max_length=500)),
                ('text', models.TextField(blank=True, help_text='Used only for Text block entries.')),
                ('media', models.FileField(blank=True, upload_to='footer/')),
                ('media_alt', models.CharField(blank=True, max_length=160)),
                ('action', models.CharField(blank=True, choices=[('cookie', 'Open cookie settings'), ('dark', 'Toggle dark mode'), ('text_size', 'Change text size'), ('motion', 'Toggle reduced motion'), ('print', 'Print page'), ('logout', 'Sign out')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.footersection')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RobotsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Path or prefix. /static/ covers every URL that starts with /static/.', max_length=240)),
                ('directive', models.CharField(choices=[('disallow', 'Disallow'), ('allow', 'Allow')], default='disallow', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('note', models.CharField(blank=True, help_text='Admin-only explanation.', max_length=160)),
            ],
            options={
                'ordering': ['sort_order', 'path', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('path', 'directive'), name='unique_robots_rule')],
            },
        ),
    ]
