# Generated by Django 5.2.17 on 2026-09-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_footeritem_quiet_and_syntaxsavr_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_header_logo',
            field=models.BooleanField(default=True, help_text='Show the uploaded header logo. The site name is used when no logo is uploaded.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_megamenu',
            field=models.BooleanField(default=True, help_text='Use the grouped megamenu. When off, the compact default navigation is shown.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_logo',
            field=models.ImageField(blank=True, upload_to='navigation/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_logo_alt',
            field=models.CharField(blank=True, help_text='Describe the uploaded logo for people who cannot see it.', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='navigation_menu_label',
            field=models.CharField(default='Menu', max_length=40),
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='Explore', help_text='Items with the same group name form one megamenu column.', max_length=80)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional supporting line shown in the megamenu.', max_length=180)),
                ('page', models.CharField(choices=[('custom', 'Custom URL'), ('home', 'Home'), ('demo', 'Demo'), ('articles', 'Articles'), ('contact', 'Contact'), ('account', 'Account'), ('login', 'Sign in'), ('register', 'Register'), ('logout', 'Sign out'), ('admin', 'Admin'), ('privacy', 'Privacy'), ('imprint', 'Imprint'), ('accessibility', 'Accessibility')], default='custom', max_length=20)),
                ('url', models.CharField(blank=True, help_text='Used only for Custom URL links.', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('site_configuration', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='core.siteconfiguration')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
