# Generated by Django 5.2.17 on 2026-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_enable_header_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='announcement_text',
            field=models.CharField(blank=True, help_text='Short banner text shown above the header while enabled.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='announcement_url',
            field=models.CharField(blank=True, help_text='Optional link target for the announcement banner.', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_accessibility_panel',
            field=models.BooleanField(default=True, help_text='Show the accessibility button in the header. It opens display options: dark mode, contrast, text size, reduced motion, print.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
