# Generated by Django 5.2.17 on 2026-09-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_move_display_options_to_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Admin-only name, e.g. 'Audit package'.", max_length=120)),
                ('buy_button_id', models.CharField(help_text='From the Stripe Buy Button code: buy-button-id.', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='stripe_buy_button_id',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_webp_conversion',
            field=models.BooleanField(default=True, help_text='Newly uploaded article images are automatically stored as WebP.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='webp_quality',
            field=models.PositiveSmallIntegerField(default=82),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='enable_stripe_buy_button',
            field=models.BooleanField(default=False, help_text='Master switch. Buy buttons come from the Stripe buttons table; the publishable key below is shared.'),
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('heading', 'Heading'), ('text', 'Paragraph'), ('quote', 'Quote'), ('image', 'Image'), ('video', 'Video'), ('buy', 'Stripe buy button'), ('divider', 'Divider')], default='text', max_length=10)),
                ('heading_level', models.CharField(blank=True, choices=[('2', 'H2'), ('3', 'H3')], default='2', help_text='Heading blocks only.', max_length=2)),
                ('text', models.TextField(blank=True, help_text='Heading, paragraph or quote text.')),
                ('quote_attribution', models.CharField(blank=True, help_text='Quote blocks only.', max_length=160)),
                ('video_file', models.FileField(blank=True, help_text='Internal video (mp4, webm).', upload_to='articles/videos/')),
                ('video_url', models.CharField(blank=True, help_text='External YouTube or Vimeo URL. Loads only after consent.', max_length=400)),
                ('video_caption', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.article')),
                ('image', models.ForeignKey(blank=True, help_text='Pick one of the images uploaded for this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='core.articleimage')),
                ('buy_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='core.stripebutton')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
