# Generated by Django 5.2.17 on 2026-09-20 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stripebutton_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_email_otp',
            field=models.BooleanField(default=False, help_text='Registration requires entering a one-time code sent by email before the account becomes active.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_message_auto_delete',
            field=models.BooleanField(default=True, help_text='Data minimisation: stored contact messages are deleted automatically after the retention window.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='message_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(default='registration', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
