# Generated by Django 5.2.17 on 2026-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfiguration_enable_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_avatar_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='anonymous_token_length',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='avatar_max_kb',
            field=models.PositiveIntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='deletion_delay_hours',
            field=models.PositiveIntegerField(default=72, help_text='Deletion executions (data and account) wait this many hours, during which the account is suspended.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_accounts',
            field=models.BooleanField(default=True, help_text='Master switch. Off removes every trace of login/registration from the site: routes answer 404, navigation entries disappear.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_login_anonymous',
            field=models.BooleanField(default=False, help_text='Access-code accounts: a random string is the credential. No email, no password.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_login_email_otp',
            field=models.BooleanField(default=False, help_text='Anti-enumeration: the same answer is shown whether or not the address exists.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_login_magic_link',
            field=models.BooleanField(default=False, help_text='Anti-enumeration: the same answer is shown whether or not the address exists.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_login_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='export_cooldown_days',
            field=models.PositiveIntegerField(default=28, help_text='Data export: minimum days between two requests per user.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='export_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Data export: archives auto-delete this many days after they were requested.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='export_wait_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Data export: minutes between request and archive availability.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='force_2fa_users',
            field=models.BooleanField(default=False, help_text="Every account (not only staff) must confirm a second factor. While on, the admin's own 2FA cannot be bypassed either."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_event_retention_days',
            field=models.PositiveIntegerField(default=14, help_text='Technical login traces (IP, agent, time) are kept at least this long and purged after.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='login_identifier_mode',
            field=models.CharField(choices=[('username', 'Username'), ('email', 'Email'), ('either', 'Username or email')], default='either', help_text='Identifier accepted by the password and code logins.', max_length=10),
        ),
    ]
