# Generated by Django 5.2.17 on 2026-09-26 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contactmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblock',
            name='video_file',
            field=models.FileField(blank=True, help_text='Internal video (mp4, webm only).', upload_to='articles/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='footeritem',
            name='media',
            field=models.FileField(blank=True, upload_to='footer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
