# Generated by Django 5.2.17 on 2026-09-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_articleblock_video_file_alter_footeritem_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('failed', 'Failed'), ('expired', 'Expired'), ('rejected', 'Rejected')], max_length=10)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('purpose', models.CharField(blank=True, max_length=300)),
                ('created_at', models.CharField(blank=True, help_text='created_at as claimed by the file', max_length=60)),
                ('detail', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ops log entry',
                'verbose_name_plural': 'Ops log',
                'ordering': ['-processed_at'],
            },
        ),
    ]
