# Generated by Django 5.2.17 on 2026-09-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_opslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Accounts & login settings',
                'verbose_name_plural': 'Accounts & login settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='ArticlesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Articles settings',
                'verbose_name_plural': 'Articles settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='CalcomSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Cal.com embed',
                'verbose_name_plural': 'Cal.com embed',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Contact form settings',
                'verbose_name_plural': 'Contact form settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Footer settings',
                'verbose_name_plural': 'Footer settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Skeleton configuration',
                'verbose_name_plural': 'Skeleton configuration',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Header & navigation settings',
                'verbose_name_plural': 'Header & navigation settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='ProtectionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Security & protection',
                'verbose_name_plural': 'Security & protection',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='RetentionSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Privacy & retention (GDPR)',
                'verbose_name_plural': 'Privacy & retention (GDPR)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
            ],
            options={
                'verbose_name': 'SEO settings',
                'verbose_name_plural': 'SEO settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='StripeSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Stripe settings',
                'verbose_name_plural': 'Stripe settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='TrackingSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking & consent settings',
                'verbose_name_plural': 'Tracking & consent settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
        migrations.CreateModel(
            name='TurnstileSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Cloudflare Turnstile',
                'verbose_name_plural': 'Cloudflare Turnstile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.siteconfiguration',),
        ),
    ]
