# Generated by Django 5.2.17 on 2026-09-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_accountssettings_articlessettings_calcomsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountssettings',
            options={'verbose_name': 'Accounts & login', 'verbose_name_plural': 'Accounts & login'},
        ),
        migrations.AlterModelOptions(
            name='articlessettings',
            options={'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='calcomsettings',
            options={'verbose_name': 'Cal.com', 'verbose_name_plural': 'Cal.com'},
        ),
        migrations.AlterModelOptions(
            name='contactformsettings',
            options={'verbose_name': 'Contact form', 'verbose_name_plural': 'Contact form'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'Header & navigation', 'verbose_name_plural': 'Header & navigation'},
        ),
        migrations.AlterModelOptions(
            name='retentionsettings',
            options={'verbose_name': 'Privacy & retention', 'verbose_name_plural': 'Privacy & retention'},
        ),
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEO'},
        ),
        migrations.AlterModelOptions(
            name='stripesettings',
            options={'verbose_name': 'Stripe', 'verbose_name_plural': 'Stripe'},
        ),
        migrations.AlterModelOptions(
            name='trackingsettings',
            options={'verbose_name': 'Tracking & consent', 'verbose_name_plural': 'Tracking & consent'},
        ),
        migrations.AlterModelOptions(
            name='turnstilesettings',
            options={'verbose_name': 'Turnstile', 'verbose_name_plural': 'Turnstile'},
        ),
    ]
