# Generated by Django 5.2.17 on 2026-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_accountssettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='enable_scraper_block',
            field=models.BooleanField(default=True, help_text='Best-effort only: 403s known scraper user agents on legal/personal-data pages. User agents are client-supplied, so this deters casual scraping - it is not access control. Real protection comes from the login wall.'),
        ),
    ]
