# Generated by Django 5.2.17 on 2026-09-26 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('body', models.TextField(help_text='Plain text shown under the checkbox.')),
                ('url', models.CharField(blank=True, help_text='Optional link, e.g. the privacy policy.', max_length=300)),
                ('required', models.BooleanField(default=True, help_text='Registration blocks until this box is ticked.')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Stored key inside profile.extra_data.', max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('text', 'Single line'), ('textarea', 'Paragraph'), ('email', 'Email'), ('phone', 'Phone'), ('address', 'Address block')], default='text', max_length=12)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready for download'), ('purged', 'Purged')], default='waiting', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('file', models.FileField(blank=True, upload_to='exports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('password', 'Password'), ('email_otp', 'Email code'), ('magic', 'Magic link'), ('anonymous', 'Access code')], default='password', max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login event',
                'verbose_name_plural': 'Login events',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailhashed', models.BooleanField(default=False)),
                ('email_hash', models.CharField(blank=True, help_text='sha256 of the lowercased email. Set when mailhashed.', max_length=64)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Token accounts: no email, no password, token IS the credential.')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Values for the admin-defined registration fields.')),
                ('data_deletion_requested', models.DateTimeField(blank=True, null=True)),
                ('data_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('account_deletion_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'slug', 'version'), name='unique_consent_version')],
            },
        ),
    ]
