# Generated by Django 5.2.17 on 2026-09-26 21:53

import accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suspended_by_data_deletion',
            field=models.BooleanField(default=False, help_text='True while the data-deletion flow owns the deactivation. Maintenance only reactivates accounts it deactivated itself.'),
        ),
        migrations.AlterField(
            model_name='dataexportrequest',
            name='file',
            field=models.FileField(blank=True, help_text='Private storage: never reachable through /media/ or any public route.', storage=accounts.storage.PrivateMediaStorage(), upload_to='exports/'),
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
