# Generated by Django 5.2.17 on 2026-09-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unique_email_ci'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consenttext',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'consent text (signup checkbox)', 'verbose_name_plural': 'consent texts (signup checkboxes)'},
        ),
        migrations.AlterModelOptions(
            name='dataexportrequest',
            options={'ordering': ['-created'], 'verbose_name': 'data export request', 'verbose_name_plural': 'data export requests'},
        ),
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-created'], 'verbose_name': 'login trace', 'verbose_name_plural': 'login traces'},
        ),
        migrations.AlterModelOptions(
            name='registrationfield',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'signup form field', 'verbose_name_plural': 'signup form fields'},
        ),
        migrations.AlterModelOptions(
            name='userconsent',
            options={'ordering': ['-accepted_at'], 'verbose_name': 'user consent acceptance', 'verbose_name_plural': 'user consent acceptances'},
        ),
        migrations.AlterField(
            model_name='consenttext',
            name='slug',
            field=models.SlugField(help_text='Internal key under which acceptances are stored. Never change it after go-live; edit the title instead.', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='consenttext',
            name='title',
            field=models.CharField(help_text="The checkbox label at registration, e.g. 'I accept the privacy policy'.", max_length=160),
        ),
        migrations.AlterField(
            model_name='consenttext',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Bump this number whenever you edit the text. Each acceptance records the version, so you can always tell which wording a user agreed to.'),
        ),
    ]
